### PR TITLE
wrong exercise (Arithmetic operations)

### PR DESCRIPTION
**Pull request by im-kulikov**
In exercise used `(10 * (4 - 6) + 15 / 3) mod 7`, bu below.. in description we have `(3 * (5 - 6) + 15 / 2) mod 3`

### CODE REVIEW

**Comment by igormcoelho** [comment]
Correct my friend, thanks a lot!

**Comment by igormcoelho** [comment]
Could you post your NEO Address here?

**Comment by vncoelho** [comment]
thanks, @im-kulikov. Nice catch and great attention.

Could you post your NEO Address here for a possible donation?

**Comment by im-kulikov** [comment]
@vncoelho AcraNnCuPKnUYtPYyrACRCVJhLpvskbfhu

**Comment by vncoelho** [comment]
https://neoscan.io/transaction/672AEEB012B63F2F2767DE410FF028100188FF90A4CF18A6D89FF9A13A2A7656

**Comment by im-kulikov** [comment]
Yeah, thanks

**Pull request merged**
